alg_type: "dqn-cts"

#dqn
learning_rate:           0.00025
momentum:                0.95
target_update_steps:     10000
batch_update_steps:      4
batch_update_size:       32
final_epsilon:           0.1
epsilon_annealing_steps: 5000000
replay_size:             1000000
arch:                    "NATURE"

#cts-specific
cts_bins:        8
cts_rescale_dim: 42